/**
 * Sound-effect port.
 *
 * Like `haptics`, consumers depend on the `Sound` interface with semantic verbs
 * (`place()`, `error()`, `win()`, …), never on Web Audio directly, so a native
 * port swaps the implementation. The web adapter loads the bundled, self-hosted
 * .ogg cues (generated by scripts/generate-sounds.mjs — no licensed assets) into
 * an AudioContext for low-latency, overlappable playback.
 *
 * Web Audio can only start after a user gesture, so the context is created +
 * unlocked on the first pointer/key event; calls before that are silent no-ops
 * (callers fire unconditionally). Muting is the caller's job (gated on the
 * `sound` setting) — the adapter just plays.
 */

import placeUrl from '../assets/audio/place.ogg';
import noteUrl from '../assets/audio/note.ogg';
import errorUrl from '../assets/audio/error.ogg';
import eraseUrl from '../assets/audio/erase.ogg';
import completeUrl from '../assets/audio/complete.ogg';
import winUrl from '../assets/audio/win.ogg';
import loseUrl from '../assets/audio/lose.ogg';

export interface Sound {
  place(): void;
  note(): void;
  erase(): void;
  error(): void;
  complete(): void;
  win(): void;
  lose(): void;
}

type Name = keyof Sound;

const URLS: Record<Name, string> = {
  place: placeUrl,
  note: noteUrl,
  erase: eraseUrl,
  error: errorUrl,
  complete: completeUrl,
  win: winUrl,
  lose: loseUrl,
};

type Ctx = AudioContext;
let ctx: Ctx | null = null;
let master: GainNode | null = null;
const buffers = new Map<Name, AudioBuffer>();

const ensureCtx = (): Ctx | null => {
  if (ctx) return ctx;
  if (typeof window === 'undefined') return null;
  const AC: typeof AudioContext | undefined =
    window.AudioContext ?? (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
  if (!AC) return null;
  ctx = new AC();
  master = ctx.createGain();
  master.gain.value = 0.55;
  master.connect(ctx.destination);
  // Preload + decode every cue once (a few KB each).
  for (const name of Object.keys(URLS) as Name[]) {
    fetch(URLS[name])
      .then((r) => r.arrayBuffer())
      .then((b) => ctx!.decodeAudioData(b))
      .then((buf) => buffers.set(name, buf))
      .catch(() => {
        /* a missing/undecodable cue just stays silent */
      });
  }
  return ctx;
};

/** Resume/create the context on the first user gesture so later plays are audible. */
const unlock = (): void => {
  const c = ensureCtx();
  if (c && c.state === 'suspended') void c.resume();
};
if (typeof window !== 'undefined') {
  const opts = { once: true, passive: true } as const;
  window.addEventListener('pointerdown', unlock, opts);
  window.addEventListener('keydown', unlock, opts);
}

const play = (name: Name): void => {
  // No gesture yet (context missing/suspended) or cue not decoded → silent.
  if (!ctx || ctx.state !== 'running' || !master) return;
  const buf = buffers.get(name);
  if (!buf) return;
  const src = ctx.createBufferSource();
  src.buffer = buf;
  src.connect(master);
  try {
    src.start();
  } catch {
    /* ignore */
  }
};

/** Web adapter over the Web Audio API. */
export const webSound: Sound = {
  place: () => play('place'),
  note: () => play('note'),
  erase: () => play('erase'),
  error: () => play('error'),
  complete: () => play('complete'),
  win: () => play('win'),
  lose: () => play('lose'),
};

/** The active sound implementation (web today; a native port swaps this binding). */
export const sound: Sound = webSound;
