/**
 * Challenge-bank loader. Each difficulty's puzzles live in their own JSON pack
 * (generated by scripts/generate-challenges.ts) and are imported dynamically so
 * the bank ships as separate lazy chunks — none of it is in the initial bundle.
 */

import type { Difficulty } from '../../engine/types';

export interface ChallengePack {
  difficulty: Difficulty;
  /** 81-char given-strings ('.' = empty). Solutions are derived at play time. */
  puzzles: string[];
}

const loaders: Record<Difficulty, () => Promise<unknown>> = {
  easy: () => import('./easy.json'),
  medium: () => import('./medium.json'),
  hard: () => import('./hard.json'),
  pro: () => import('./pro.json'),
  impossible: () => import('./impossible.json'),
};

const cache = new Map<Difficulty, ChallengePack>();

/** Load (and memoize) the puzzle pack for a difficulty. */
export const loadChallengePack = async (
  difficulty: Difficulty,
): Promise<ChallengePack> => {
  const cached = cache.get(difficulty);
  if (cached) return cached;

  const mod = (await loaders[difficulty]()) as
    | ChallengePack
    | { default: ChallengePack };
  const pack = 'default' in mod ? mod.default : mod;
  cache.set(difficulty, pack);
  return pack;
};
