/**
 * Challenge-bank loader. Each difficulty's puzzles live in their own JSON pack
 * (generated by scripts/generate-challenges.ts) and are imported dynamically so
 * the bank ships as separate lazy chunks — none of it is in the initial bundle.
 */

import type { Difficulty } from '@sudoku/core';

export interface ChallengePack {
  difficulty: Difficulty;
  /** 81-char given-strings ('.' = empty). Solutions are derived at play time. */
  puzzles: string[];
}

/**
 * Puzzle count per pack. Kept as a tiny static map so screens can show totals
 * ("12 / 60 solved") without importing (and holding in memory) the JSON packs
 * themselves. A test asserts these stay in sync with the actual packs.
 */
export const PACK_SIZES: Record<Difficulty, number> = {
  easy: 60,
  medium: 60,
  hard: 50,
  pro: 40,
  impossible: 30,
};

const loaders: Record<Difficulty, () => Promise<unknown>> = {
  easy: () => import('./easy.json'),
  medium: () => import('./medium.json'),
  hard: () => import('./hard.json'),
  pro: () => import('./pro.json'),
  impossible: () => import('./impossible.json'),
};

const cache = new Map<Difficulty, ChallengePack>();

/** Load (and memoize) the puzzle pack for a difficulty. */
export const loadChallengePack = async (
  difficulty: Difficulty,
): Promise<ChallengePack> => {
  const cached = cache.get(difficulty);
  if (cached) return cached;

  const mod = (await loaders[difficulty]()) as
    | ChallengePack
    | { default: ChallengePack };
  const pack = 'default' in mod ? mod.default : mod;
  cache.set(difficulty, pack);
  return pack;
};
